# Generated by Django 6.0.3 on 2026-04-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='reason',
            new_name='rejection_reason',
        ),
    ]
