# Generated by Django 6.0.3 on 2026-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_reason_application_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_response_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accept', 'Accept'), ('reject', 'Reject')], max_length=10, null=True),
        ),
    ]
