# Generated by Django 6.0.3 on 2026-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interview_note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
