# Generated by Django 6.0.3 on 2026-04-03 13:27

import django.db.models.deletion
import jobs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time')], max_length=20)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('deadline', models.DateTimeField(blank=True, default=jobs.models.default_deadline)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminate_at', models.DateTimeField(blank=True, default=jobs.models.default_job_expiry)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('live', 'Live'), ('closed', 'Closed')], default='live', editable=False, max_length=10)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
