# Generated by Django 6.0.3 on 2026-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='terminated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
