# Generated by Django 6.0.3 on 2026-04-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_terminated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='deadline',
            new_name='application_deadline',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_description',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('office', 'Office')], max_length=20),
        ),
    ]
