# Generated by Django 6.0.3 on 2026-04-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_deadline_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('data', 'Data Science / AI'), ('devops', 'DevOps / Cloud'), ('mobile', 'Mobile Development'), ('uiux', 'UI/UX Design'), ('qa', 'QA / Testing'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
