# Generated by Django 6.0.3 on 2026-04-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_benefits_job_experience_job_map_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='currency',
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
