# Generated by Django 6.0.3 on 2026-04-22 15:05

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, default=jobs.models.default_deadline),
        ),
        migrations.AlterField(
            model_name='job',
            name='terminate_at',
            field=models.DateField(blank=True, default=jobs.models.default_job_expiry),
        ),
    ]
