# Generated by Django 6.0.3 on 2026-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('applications_closed', 'Applications Closed'), ('closed', 'Closed')], default='live', editable=False, max_length=20),
        ),
    ]
