# Generated by Django 6.0.3 on 2026-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('mobile_android', 'Android Developer'), ('mobile_ios', 'iOS Developer'), ('mobile_cross', 'Cross Platform Developer'), ('data_science', 'Data Scientist'), ('data_analyst', 'Data Analyst'), ('ml_engineer', 'Machine Learning Engineer'), ('ai_engineer', 'AI Engineer'), ('devops', 'DevOps Engineer'), ('cloud', 'Cloud Engineer'), ('sre', 'Site Reliability Engineer'), ('cybersecurity', 'Cybersecurity Specialist'), ('network', 'Network Engineer'), ('database', 'Database Administrator'), ('bigdata', 'Big Data Engineer'), ('uiux', 'UI/UX Designer'), ('product_designer', 'Product Designer'), ('qa_manual', 'QA Engineer (Manual)'), ('qa_automation', 'QA Engineer (Automation)'), ('embedded', 'Embedded Systems Engineer'), ('iot', 'IoT Developer'), ('game_dev', 'Game Developer'), ('ar_vr', 'AR/VR Developer'), ('blockchain', 'Blockchain Developer'), ('web3', 'Web3 Developer'), ('system_admin', 'System Administrator'), ('it_support', 'IT Support Engineer'), ('erp', 'ERP/CRM Developer'), ('sap', 'SAP Consultant'), ('technical_writer', 'Technical Writer'), ('business_analyst', 'Business Analyst'), ('project_manager', 'Project Manager'), ('product_manager', 'Product Manager'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
