# Generated by Django 6.0.3 on 2026-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applications_closed',
            field=models.BooleanField(default=False),
        ),
    ]
