# Generated by Django 6.0.3 on 2026-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
