# Generated by Django 6.0.3 on 2026-04-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
