# Generated by Django 6.0.3 on 2026-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidate_college_name_candidate_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
