# Generated by Django 6.0.3 on 2026-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_candidate_github_link_candidate_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
