# Generated by Django 6.0.3 on 2026-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_candidate_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
