# Generated by Django 6.0.3 on 2026-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_is_verified_candidate_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
