# Generated by Django 6.0.3 on 2026-04-16 18:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_company_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='username',
            field=models.SlugField(max_length=18, unique=True, validators=[accounts.models.username_validator]),
        ),
    ]
